import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const defaultItems = {
  'my-cool-product': {
    id: 'my-cool-product',
    name: 'My Cool Product',
    price: 24.99,
    quantity: 3
  },
  'my-premium-product': {
    id: 'my-premium-product',
    name: 'My Premium Product',
    price: 84.99,
    quantity: 1
  },
};

const defaultSettings = {
  discount: .2,
  tax: .06
}

const defaultOrder = {};

export default function Home() {
  const [items, setItems] = useState(defaultItems);
  const [settings, setSettings] = useState(defaultSettings);
  const [order, setOrder] = useState(defaultOrder);

  function handleOnSubmitAddItem(e) {
    e.preventDefault();

    const formData = new FormData(e.currentTarget);
    const name = formData.get('name');
    const id = formData.get('id');
    const quantity = parseInt(formData.get('quantity'));
    const price = formData.get('price');

    if ( items[id] ) {
      setItems(prev => {
        return {
          ...prev,
          [id]: {
            ...items[id],
            quantity: items[id].quantity + quantity
          }
        }
      })
    } else {
      setItems(prev => {
        return {
          ...prev,
          [id]: {
            name,
            id,
            quantity,
            price
          }
        }
      })
    }

  }

  function handleOnSubmitUpdateSettings(e) {
    e.preventDefault();

    const formData = new FormData(e.currentTarget);
    const discount = formData.get('discount');
    const tax = formData.get('tax');

    setSettings({
      discount,
      tax
    })
  }

  async function handleOnSubmitCalculateOrder(e) {
    e.preventDefault();

    const results = await fetch('/api/cart', {
      method: 'POST',
      body: JSON.stringify({
        items: Object.keys(items).map(key => items[key]),
        ...settings
      })
    }).then(response => response.json());

    setOrder(results);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Store
        </h1>

        <div className={styles.body}>
          <div>
            <h2>Add Items</h2>
            <form className={styles.form} onSubmit={handleOnSubmitAddItem}>
              <div className={styles.formRow}>
                <label>Name</label>
                <input name="name" type="text" />
              </div>
              <div className={styles.formRow}>
                <label>ID</label>
                <input name="id" type="text" />
              </div>
              <div className={styles.formRow}>
                <label>Quantity</label>
                <input name="quantity" type="number" step={1} />
              </div>
              <div className={styles.formRow}>
                <label>Price</label>
                <input name="price" type="number" step={1} />
              </div>
              <div className={styles.formRow}>
                <button>Add item</button>
              </div>
            </form>

            <h2>Order Settings</h2>
            <form className={styles.form} onSubmit={handleOnSubmitUpdateSettings}>
              <div className={styles.formRow}>
                <label>Discount</label>
                <input name="discount" type="number" defaultValue={settings.discount} step={.01} />
              </div>
              <div className={styles.formRow}>
                <label>Tax</label>
                <input name="tax" type="number" defaultValue={settings.tax} step={.01} />
              </div>
              <div className={styles.formRow}>
                <button>Update</button>
              </div>
            </form>
          </div>

          <div>
            <h2>Cart</h2>
            <ul className={styles.items}>
              {Object.keys(items).map(key => {
                const item = items[key]
                return (
                  <li key={item.id}>
                    <h3>{ item.name }</h3>
                    <p>{ item.quantity } @ ${ item.price } each</p>
                  </li>
                )
              })}
            </ul>

            <h2>Order</h2>
            <form onSubmit={handleOnSubmitCalculateOrder}>
              <button>Calculate Order</button>
            </form>
            <ul className={styles.orderDetails}>
              <li>
                Subtotal: { order.subtotal }
              </li>
              <li>
                Discount: { order.discount }
              </li>
              <li>
                Tax: { order.tax }
              </li>
              <li>
                Total: { order.total }
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  )
}
